services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:80"
    volumes:
      #root webu
      - ./src:/var/www/html
      #konfigurace apache
      - .apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      #php.ini
      #- .apache/php.ini-development:/usr/local/etc/php/php.ini-development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: testdb
    volumes:
      #pokud by měla být data persistentní
      #- ./db_data:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      #konstanty jsou v souboru .env, případně .env.local ....
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      #port phpmyadmin
      - "${PHP_MYADMIN_PORT}:80"
    depends_on:
      #závislost na db kontejneru
      - db